# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('date_naiss', models.DateField(auto_now=True)),
                ('num', models.IntegerField(max_length=6)),
                ('parcours', models.CharField(max_length=2)),
            ],
        ),
    ]
