# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='num',
            field=models.IntegerField(),
        ),
    ]
