# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_auto_20180529_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('coef', models.IntegerField()),
                ('unite', models.CharField(max_length=30)),
                ('parcours', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.Module')),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_naiss',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(choices=[('Informatique', 'Informatique')], default='Informatique', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='parcours',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=2),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='specialite',
            field=models.CharField(choices=[("Systeme d'information", "Systeme d'information")], default="Systeme d'information", max_length=21),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='moyennes',
            field=models.ManyToManyField(to='etudiants.Moyenne'),
        ),
    ]
